### ISSUE TITLE
Add Distinct Keybinds using Numeric Keypad Keys

### ISSUE THREAD

**Issue by SeparGW2** [BoyC/GW2TacO#99] opened 2022-04-09 20:58 UTC
064.3695r
Keybinds do not distinguish between numeric keypad keys and the keys on the standard keyboard that product the same character.

The GW2 keybind interface distinguishes between the standard and numeric keypad keys like this: 7 and 7 (NUM).  

For keybinding, each of the keys on the numeric keypad - Divide (NUM), Multiply (NUM), Subtract (NUM), Add (NUM), Return (NUM), 0 (NUM) to 9 (NUM) - should be interpreted as different from the keys on the standard keyboard that produce the same characters.

**Comment by BoyC** [comment] 2022-04-09 21:02
Duplicate of #73

**Closed by BoyC** 2022-04-09 21:02 UTC
Labels: duplicate
